### ISSUE TITLE
解决图片自适应宽度居中问题

### ISSUE THREAD

**Issue by FamousMai** [FamousMai/css-problem-solving#1]
### html 代码
```html
<div class="yourdiv">
      <img src="" alt="">
      <div class="dummy"></div>
<div>
```
### css 代码
```css
.yourdiv{
  text-align: left;
  overflow: hidden; 
  display: block; 
  text-align:center; 
  position: relative;
}

.yourdiv .dummy { 
  padding-top: 100%; 
}

.yourdiv img {
  -webkit-transition: all 0.3s ease-out 0s;
  -o-transition: all 0.3s ease-out 0s;
  transition: all 0.3s ease-out 0s;
  overflow: hidden; 
  margin: auto; 
  position: absolute; top: 0; 
  bottom: 0; left: 0; right: 0;
  display: block;  
}
```
- 稍微解释一下 dummy起到一个占位置的作用 具体原理我也不是特别理解 知道的伙伴欢迎评论
- 最终效果，不管引入多少宽度的图片，都会自适应yourdiv的最大宽度，且水平垂直居中
